import type { Metadata } from "next";
import { Inter, Jost } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });
const jost = Jost({ subsets: ['latin'] })

export const metadata = {
  title: 'AssessAI | Smart Assessment',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en">

      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16x16.png" />
        <link rel="manifest" href="/assets/favicon/site.webmanifest" />
        <link rel="mask-icon" href="/assets/favicon/safari-pinned-tab.svg" color="#5bbad5" />
        <link rel="shortcut icon" href="/assets/favicon/favicon.ico" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="msapplication-config" content="/assets/favicon/browserconfig.xml" />
        <meta name="theme-color" content="#ffffff" />
      </head>

      <body className={jost.className}>
        <Provider session={session}>
          {children}
        </Provider>

      </body>
    </html>
  );
}
