import Sidebar from "@/components/Sidebar"


export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Sidebar />
      <div className="w-full ml-0 sm:pl-[calc(30%+0.75rem)] lg:pl-[calc(20%+1.5rem)] mt-16 p-4 sm:p-6 lg:p-8 flex justify-center">
        {children}
      </div>


    </>
  )
}
